#!/bin/bash
set -e
set -x

EXAMPLESDIR="$PWD/examples"
cd $AUTOPKGTEST_TMP

examples="$(find $EXAMPLESDIR -mindepth 1 -maxdepth 1 -type d -printf '%f\n')"
for example in ${examples}; do
  mkdir build-${example}
  pushd build-${example} >/dev/null

  cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_VERBOSE_MAKEFILE=ON "$EXAMPLESDIR/${example}"
  make

  popd >/dev/null
done
